[package]
name = "Find_Valid_Matrix_Given_Row_and_Column_Sums"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
